name: Run Autolisting Scraper

on:
  schedule:
    - cron: "*/15 * * * *"  # runs every 15 minutes
  workflow_dispatch:  # allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py